import type { ResearchColumnDefinition } from '@metrev/domain-contracts';

export const DEFAULT_RESEARCH_COLUMNS: ResearchColumnDefinition[] = [
  {
    column_id: 'paper',
    name: 'Paper',
    group: 'identification',
    type: 'metadata',
    answer_structure: 'paper_metadata',
    instructions:
      'Return title, authors, year, DOI, journal, source URL, and PDF availability from stored metadata.',
    output_schema_key: 'paper_metadata',
    output_schema: {},
    visible: true,
    position: 0,
  },
  {
    column_id: 'summary',
    name: 'Summary',
    group: 'synthesis',
    type: 'deterministic',
    answer_structure: 'specified',
    instructions:
      'Summarize only the stored abstract or title. Do not add unsupported claims.',
    output_schema_key: 'summary',
    output_schema: {
      summary: 'string | null',
      evidence_span: 'string | null',
      confidence: 'low | medium | high',
    },
    visible: true,
    position: 1,
  },
  {
    column_id: 'technology_application',
    name: 'Technology & Application',
    group: 'application',
    type: 'deterministic',
    answer_structure: 'specified',
    instructions:
      'Extract technology class, application, scale, and wastewater-energy context explicitly mentioned in the source.',
    output_schema_key: 'technology_application',
    output_schema: {},
    visible: true,
    position: 2,
  },
  {
    column_id: 'design_parameters',
    name: 'Design Parameters',
    group: 'bioelectrochemistry',
    type: 'deterministic',
    answer_structure: 'system_performance_subset',
    instructions:
      'Extract reactor architecture, electrode configuration, separator, volume, geometry, and external circuit details when stated.',
    output_schema_key: 'system_performance',
    output_schema: {},
    visible: true,
    position: 3,
  },
  {
    column_id: 'material_properties',
    name: 'Material Properties',
    group: 'bioelectrochemistry',
    type: 'deterministic',
    answer_structure: 'system_performance_subset',
    instructions:
      'Extract anode, cathode, membrane/separator, current collector, and stated material properties.',
    output_schema_key: 'system_performance',
    output_schema: {},
    visible: true,
    position: 4,
  },
  {
    column_id: 'operating_conditions',
    name: 'Operating Conditions',
    group: 'bioelectrochemistry',
    type: 'deterministic',
    answer_structure: 'system_performance_subset',
    instructions:
      'Extract pH, temperature, conductivity, salinity, HRT, flow mode, substrate/feedstock, and operating regime when stated.',
    output_schema_key: 'system_performance',
    output_schema: {},
    visible: true,
    position: 5,
  },
  {
    column_id: 'performance_metrics',
    name: 'Performance Metrics',
    group: 'metrics',
    type: 'deterministic',
    answer_structure: 'system_performance_subset',
    instructions:
      'Extract electrochemical, efficiency, treatment, and product metrics with units and evidence spans.',
    output_schema_key: 'system_performance',
    output_schema: {},
    visible: true,
    position: 6,
  },
  {
    column_id: 'product_outputs',
    name: 'Product Outputs',
    group: 'metrics',
    type: 'deterministic',
    answer_structure: 'system_performance_subset',
    instructions:
      'Extract H2, methane, acetate, desalination, recovered chemicals, or other product outputs when stated.',
    output_schema_key: 'system_performance',
    output_schema: {},
    visible: true,
    position: 7,
  },
  {
    column_id: 'limitations',
    name: 'Limitations',
    group: 'limitations',
    type: 'deterministic',
    answer_structure: 'implementation_factors_subset',
    instructions:
      'Extract explicitly stated limitations, challenges, fouling, resistance, scale-up, cost, durability, and reproducibility issues.',
    output_schema_key: 'implementation_factors',
    output_schema: {},
    visible: true,
    position: 8,
  },
  {
    column_id: 'implementation_factors',
    name: 'Implementation Factors',
    group: 'decision',
    type: 'deterministic',
    answer_structure: 'implementation_factors',
    instructions:
      'Extract TRL, maturity, supplier relevance, environmental/safety factors, implementation dependencies, and scale-up barriers.',
    output_schema_key: 'implementation_factors',
    output_schema: {},
    visible: true,
    position: 9,
  },
  {
    column_id: 'objectives',
    name: 'Objectives',
    group: 'scientific_structure',
    type: 'llm_extracted',
    answer_structure: 'specified',
    instructions: 'Extract explicitly stated study objectives.',
    output_schema_key: 'generic_list',
    output_schema: { items: ['string'], evidence_span: 'string | null' },
    visible: false,
    position: 10,
  },
  {
    column_id: 'findings',
    name: 'Findings',
    group: 'scientific_structure',
    type: 'llm_extracted',
    answer_structure: 'specified',
    instructions: 'Extract explicitly stated findings.',
    output_schema_key: 'generic_list',
    output_schema: { items: ['string'], evidence_span: 'string | null' },
    visible: false,
    position: 11,
  },
  {
    column_id: 'research_gaps',
    name: 'Research Gaps',
    group: 'limitations',
    type: 'llm_extracted',
    answer_structure: 'specified',
    instructions:
      'Extract unresolved research gaps related to microbial electrochemical technologies.',
    output_schema_key: 'generic_list',
    output_schema: {
      gaps: ['string'],
      evidence_span: 'string | null',
      confidence: 'low | medium | high',
    },
    visible: false,
    position: 12,
  },
  {
    column_id: 'future_research',
    name: 'Future Research',
    group: 'limitations',
    type: 'llm_extracted',
    answer_structure: 'specified',
    instructions: 'Extract explicitly stated future research directions.',
    output_schema_key: 'generic_list',
    output_schema: { items: ['string'], evidence_span: 'string | null' },
    visible: false,
    position: 13,
  },
  {
    column_id: 'dependent_variables',
    name: 'Dependent Variables',
    group: 'scientific_structure',
    type: 'llm_extracted',
    answer_structure: 'specified',
    instructions:
      'Extract measured dependent variables when explicitly stated.',
    output_schema_key: 'generic_list',
    output_schema: { items: ['string'], evidence_span: 'string | null' },
    visible: false,
    position: 14,
  },
  {
    column_id: 'independent_variables',
    name: 'Independent Variables',
    group: 'scientific_structure',
    type: 'llm_extracted',
    answer_structure: 'specified',
    instructions:
      'Extract controlled independent variables when explicitly stated.',
    output_schema_key: 'generic_list',
    output_schema: { items: ['string'], evidence_span: 'string | null' },
    visible: false,
    position: 15,
  },
  {
    column_id: 'dataset',
    name: 'Data Set',
    group: 'scientific_structure',
    type: 'llm_extracted',
    answer_structure: 'specified',
    instructions:
      'Extract dataset or experimental sample description when explicitly stated.',
    output_schema_key: 'generic_list',
    output_schema: { items: ['string'], evidence_span: 'string | null' },
    visible: false,
    position: 16,
  },
  {
    column_id: 'population_sample',
    name: 'Population Sample',
    group: 'scientific_structure',
    type: 'llm_extracted',
    answer_structure: 'specified',
    instructions:
      'Extract population, inoculum, microbial sample, or wastewater sample description when stated.',
    output_schema_key: 'generic_list',
    output_schema: { items: ['string'], evidence_span: 'string | null' },
    visible: false,
    position: 17,
  },
];

export function getDefaultResearchColumns(): ResearchColumnDefinition[] {
  return DEFAULT_RESEARCH_COLUMNS.map((column) => ({ ...column }));
}

export function findDefaultResearchColumn(
  columnId: string,
): ResearchColumnDefinition | undefined {
  return getDefaultResearchColumns().find(
    (column) => column.column_id === columnId,
  );
}
